$blossomProMenu = `menu -p $gMainWindow -label "BlossomPro"`;
	menuItem -label "unitTest" -command "unitTest";
	menuItem -label "createTestWindow" -command "createTestWindow";
	menuItem -label "createPhyllotaxisWindow" -command "createPhyllotaxisWindow";
	menuItem -label "createBSplineSurface" -command "createBSplineSurfaceWindow";
	menuItem -label "curveInstance" -command "curveInstanceWindow";
	menuItem -label "createBranchEditor" -command "createBranchWindow";